```{r}
## WORK Vs CUPS

coffee_survey$cups <- as.numeric(as.character(coffee_survey$cups))
coffee_survey$wfh <- as.factor(coffee_survey$wfh)

# Handle missing values
coffee_survey <- coffee_survey %>% drop_na(cups, wfh)

ggplot(coffee_survey, aes(x = wfh, y = cups, fill = wfh)) +
  geom_boxplot() +
  labs(title = "Distribution of Cups of Coffee by Work From Home Status",
       x = "Work From Home Status",
       y = "Number of Cups of Coffee") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2")

ggplot(coffee_survey, aes(x = wfh, y = cups, fill = wfh)) +
  geom_violin() +
  labs(title = "Violin Plot of Coffee Consumption by Work From Home Status",
       x = "Work From Home Status",
       y = "Number of Cups of Coffee") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2")

ggplot(coffee_survey, aes(x = cups, fill = wfh)) +
  geom_density(alpha = 0.5) +
  labs(title = "Density Plot of Coffee Consumption by Work From Home Status",
       x = "Number of Cups of Coffee",
       y = "Density") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2")
```



```{r}
## WORK Vs STRENGTH

coffee_survey <- coffee_survey %>% drop_na(strength, wfh)

coffee_survey %>%
  ggplot(aes(x = strength, fill = strength)) +
  geom_bar() +
  facet_wrap(~ wfh) +
  labs(title = "Coffee Strength by Work From Home Status",
       x = "Coffee Strength",
       y = "Count") +
  theme_minimal() +
  scale_fill_brewer(palette = "Set2")


```

